# Generated by Django 4.2.7 on 2023-11-11 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_uz", models.CharField(max_length=31)),
                ("name_ru", models.CharField(max_length=31)),
                ("name_en", models.CharField(max_length=31)),
                ("img", models.ImageField(upload_to="category/")),
            ],
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_uz", models.CharField(max_length=31)),
                ("name_ru", models.CharField(max_length=31)),
                ("name_en", models.CharField(max_length=31)),
                ("summary_uz", models.CharField(max_length=255)),
                ("summary_ru", models.CharField(max_length=255)),
                ("summary_en", models.CharField(max_length=255)),
                ("img", models.ImageField(upload_to="subcategory/")),
                ("video", models.FileField(upload_to="videos/")),
                ("description_uz", models.TextField()),
                ("description_ru", models.TextField()),
                ("description_en", models.TextField()),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.category",
                    ),
                ),
            ],
        ),
    ]
