# Generated by Django 4.2.7 on 2023-11-11 06:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subcategory",
            old_name="subcategory",
            new_name="category",
        ),
    ]
