# Generated by Django 4.2.7 on 2023-11-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                default=" ",
                error_messages={
                    "unique": "A user with that phone number already exists."
                },
                help_text="Required. 13 digits and + .",
                max_length=13,
                unique=True,
                verbose_name="phone number",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Photo"
            ),
        ),
    ]
